"""
yoga_dosha_engine.py — Yoga and Dosha detection engine.

Pure deterministic rule-based pattern matching — zero LLM calls.
Detects classical Parashari yogas (planetary combinations) and doshas
(afflictions) from a natal chart using structured rule evaluation.

Rule evaluation is fully deterministic: each yoga/dosha is defined by
a Python function that takes a NatalChart and returns a match result.

Yoga categories implemented:
    - Pancha Mahapurusha Yogas (Hamsa, Malavya, Ruchaka, Bhadra, Shasha)
    - Raj Yogas (Kendra-Kona lord connections)
    - Dhana Yogas (2nd/11th lord connections)
    - Gajakesari Yoga
    - Budhaditya Yoga
    - Chandra-Mangala Yoga
    - Amala Yoga
    - Vesi/Vosi/Ubhayachari Yogas

Dosha categories implemented:
    - Mangal Dosha (Kuja Dosha)
    - Kala Sarpa Dosha
    - Grahan Dosha (solar/lunar eclipse)
    - Kemdrum Yoga (Moon isolation dosha)
    - Guru Chandala Yoga (Jupiter-Rahu conjunction)
    - Shrapit Dosha (Saturn-Rahu conjunction)

All results are structured (not prose) — the Synthesis Agent uses these
structured results to build natural language descriptions.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Callable, Optional

from vedic_astro.engines.natal_engine import (
    BhavaData,
    Dignity,
    NatalChart,
    OWN_SIGNS,
    PlanetName,
    PlanetPosition,
    SIGN_LORDS,
)

# ─────────────────────────────────────────────────────────────────────────────
# Enumerations
# ─────────────────────────────────────────────────────────────────────────────

class YogaCategory(str, Enum):
    MAHAPURUSHA = "mahapurusha"
    RAJ_YOGA    = "raj_yoga"
    DHANA_YOGA  = "dhana_yoga"
    LUNAR_YOGA  = "lunar_yoga"
    SOLAR_YOGA  = "solar_yoga"
    SPECIAL     = "special"


class DoshaCategory(str, Enum):
    MANGAL     = "mangal_dosha"
    KALA_SARPA = "kala_sarpa_dosha"
    GRAHAN     = "grahan_dosha"
    ISOLATION  = "isolation_dosha"
    CURSE      = "curse_dosha"


class YogaSeverity(str, Enum):
    STRONG   = "strong"    # All conditions met perfectly
    MODERATE = "moderate"  # Core conditions met, some weakening factors
    WEAK     = "weak"      # Conditions partially met


# ─────────────────────────────────────────────────────────────────────────────
# Data classes
# ─────────────────────────────────────────────────────────────────────────────

@dataclass(frozen=True)
class YogaResult:
    """
    Result of a yoga detection. Returned by each yoga detector function.
    Contains structured data only — prose is generated by the LLM layer.
    """
    name: str
    is_present: bool
    category: YogaCategory
    severity: Optional[YogaSeverity]       # None if not present
    strength: float                         # 0.0–1.0
    contributing_planets: list[PlanetName]
    key_houses: list[int]                   # Houses involved in this yoga
    effect_domain: list[str]               # e.g. ["career", "wealth"]
    source: str                             # Classical text reference
    conditions_met: list[str]              # Human-readable list of conditions satisfied
    conditions_failed: list[str]           # Conditions that weakened/prevented the yoga


@dataclass(frozen=True)
class DoshaResult:
    """
    Result of a dosha detection.
    """
    name: str
    is_present: bool
    category: DoshaCategory
    severity: float                         # 0.0–1.0 (0 = absent, 1 = full dosha)
    trigger_planets: list[PlanetName]
    trigger_houses: list[int]
    effect_domain: list[str]
    cancellation_factors: list[str]         # Classical cancellation rules met (mitigations)
    source: str


@dataclass
class YogaDoshaBundle:
    """
    Complete yoga and dosha analysis for a natal chart.
    Produced by detect_all_yogas_and_doshas() — the main public API.
    """
    chart_id: str
    yogas: list[YogaResult]
    doshas: list[DoshaResult]

    @property
    def active_yogas(self) -> list[YogaResult]:
        """Yogas that are present (is_present=True)."""
        return [y for y in self.yogas if y.is_present]

    @property
    def active_doshas(self) -> list[DoshaResult]:
        """Doshas that are present and not fully cancelled."""
        return [d for d in self.doshas if d.is_present and d.severity > 0.0]

    @property
    def net_yoga_strength(self) -> float:
        """Sum of yoga strengths (active yogas only), normalized to 0–1."""
        if not self.active_yogas:
            return 0.0
        total = sum(y.strength for y in self.active_yogas)
        return min(1.0, total / max(1, len(self.active_yogas)))

    @property
    def net_dosha_severity(self) -> float:
        """Average dosha severity (active doshas only)."""
        if not self.active_doshas:
            return 0.0
        return sum(d.severity for d in self.active_doshas) / len(self.active_doshas)


# ─────────────────────────────────────────────────────────────────────────────
# Utility helpers
# ─────────────────────────────────────────────────────────────────────────────

def _house_of(planet: PlanetName, chart: NatalChart) -> int:
    """Return the house (1–12) that a planet occupies in the natal chart."""
    return chart.planets[planet].house


def _sign_of(planet: PlanetName, chart: NatalChart) -> int:
    """Return the sign (1–12) that a planet occupies."""
    return chart.planets[planet].sign_number


def _dignity_of(planet: PlanetName, chart: NatalChart) -> Dignity:
    """Return the dignity of a planet in the natal chart."""
    return chart.planets[planet].dignity


def _is_in_kendra(planet: PlanetName, chart: NatalChart) -> bool:
    """True if planet is in a Kendra house (1, 4, 7, 10)."""
    return _house_of(planet, chart) in (1, 4, 7, 10)


def _is_in_kona(planet: PlanetName, chart: NatalChart) -> bool:
    """True if planet is in a Kona (trine) house (1, 5, 9)."""
    return _house_of(planet, chart) in (1, 5, 9)


def _is_exalted_or_own(planet: PlanetName, chart: NatalChart) -> bool:
    """True if planet is in exaltation or own sign."""
    return _dignity_of(planet, chart) in (Dignity.EXALTED, Dignity.OWN, Dignity.MOOLATRIKONA)


def _lord_of_house(house: int, chart: NatalChart) -> PlanetName:
    """Return the planetary lord of a given house in the natal chart."""
    sign = chart.bhavas[house].sign_number
    return SIGN_LORDS[sign]


def _planets_in_house(house: int, chart: NatalChart) -> list[PlanetName]:
    """Return all planets occupying a given house."""
    return chart.bhavas[house].occupants


def _are_conjunct(p1: PlanetName, p2: PlanetName, chart: NatalChart) -> bool:
    """True if two planets are in the same sign (whole-sign conjunction)."""
    return _sign_of(p1, chart) == _sign_of(p2, chart)


def _house_distance(from_house: int, to_house: int) -> int:
    """1-based house distance: how many houses from from_house to to_house."""
    return ((to_house - from_house) % 12) + 1


def _aspects_house(planet: PlanetName, target_house: int, chart: NatalChart) -> bool:
    """
    Check if a planet aspects a given house via Vedic drishti.
    All planets aspect the 7th from themselves.
    Mars: also 4th and 8th. Jupiter: also 5th and 9th. Saturn: also 3rd and 10th.
    """
    planet_house = _house_of(planet, chart)
    special_aspects: dict[PlanetName, list[int]] = {
        PlanetName.MARS:    [4, 8],
        PlanetName.JUPITER: [5, 9],
        PlanetName.SATURN:  [3, 10],
    }
    offsets = [7] + special_aspects.get(planet, [])
    aspected_houses = [((planet_house - 1 + off - 1) % 12) + 1 for off in offsets]
    return target_house in aspected_houses


def _compute_yoga_strength(
    planet: PlanetName,
    chart: NatalChart,
    base_strength: float = 0.8,
) -> float:
    """
    Compute yoga strength based on planetary dignity.
    Exalted/Moolatrikona → full strength; Debilitated → minimal.
    """
    dignity_multipliers = {
        Dignity.EXALTED:      1.0,
        Dignity.MOOLATRIKONA: 0.9,
        Dignity.OWN:          0.8,
        Dignity.FRIEND:       0.65,
        Dignity.NEUTRAL:      0.5,
        Dignity.ENEMY:        0.35,
        Dignity.DEBILITATED:  0.15,
    }
    mult = dignity_multipliers.get(_dignity_of(planet, chart), 0.5)
    return round(base_strength * mult, 3)


# ─────────────────────────────────────────────────────────────────────────────
# Yoga detector registry
# ─────────────────────────────────────────────────────────────────────────────

YogaDetector = Callable[[NatalChart], YogaResult]
DoshaDetector = Callable[[NatalChart], DoshaResult]

_YOGA_DETECTORS: list[YogaDetector] = []
_DOSHA_DETECTORS: list[DoshaDetector] = []


def yoga_detector(fn: YogaDetector) -> YogaDetector:
    """Decorator to register a yoga detector function."""
    _YOGA_DETECTORS.append(fn)
    return fn


def dosha_detector(fn: DoshaDetector) -> DoshaDetector:
    """Decorator to register a dosha detector function."""
    _DOSHA_DETECTORS.append(fn)
    return fn


# ─────────────────────────────────────────────────────────────────────────────
# Yoga detectors
# ─────────────────────────────────────────────────────────────────────────────

def _detect_mahapurusha(
    planet: PlanetName,
    yoga_name: str,
    chart: NatalChart,
    source: str,
    domains: list[str],
) -> YogaResult:
    """
    Generic detector for Pancha Mahapurusha Yogas.
    Condition: Planet must be in a Kendra house AND in exaltation or own sign.
    """
    in_kendra = _is_in_kendra(planet, chart)
    in_strength = _is_exalted_or_own(planet, chart)
    is_present = in_kendra and in_strength

    strength = _compute_yoga_strength(planet, chart) if is_present else 0.0
    severity = (
        YogaSeverity.STRONG if _dignity_of(planet, chart) == Dignity.EXALTED
        else YogaSeverity.MODERATE if is_present
        else None
    )

    met: list[str] = []
    failed: list[str] = []
    if in_kendra:
        met.append(f"{planet.value.title()} is in Kendra (house {_house_of(planet, chart)})")
    else:
        failed.append(f"{planet.value.title()} not in Kendra (house {_house_of(planet, chart)})")
    if in_strength:
        met.append(f"{planet.value.title()} is {_dignity_of(planet, chart).value}")
    else:
        failed.append(f"{planet.value.title()} is {_dignity_of(planet, chart).value} (not exalted/own)")

    return YogaResult(
        name=yoga_name,
        is_present=is_present,
        category=YogaCategory.MAHAPURUSHA,
        severity=severity,
        strength=strength,
        contributing_planets=[planet],
        key_houses=[_house_of(planet, chart)],
        effect_domain=domains,
        source=source,
        conditions_met=met,
        conditions_failed=failed,
    )


@yoga_detector
def detect_hamsa_yoga(chart: NatalChart) -> YogaResult:
    """
    Hamsa Yoga — Jupiter in Kendra in own/exaltation sign.
    Effects: wisdom, spiritual elevation, fame, children.
    Source: BPHS ch. 35
    """
    return _detect_mahapurusha(
        PlanetName.JUPITER, "Hamsa Yoga", chart,
        "BPHS ch. 35", ["spirituality", "wisdom", "general"],
    )


@yoga_detector
def detect_malavya_yoga(chart: NatalChart) -> YogaResult:
    """
    Malavya Yoga — Venus in Kendra in own/exaltation sign.
    Effects: beauty, luxury, prosperity, spouse.
    Source: BPHS ch. 35
    """
    return _detect_mahapurusha(
        PlanetName.VENUS, "Malavya Yoga", chart,
        "BPHS ch. 35", ["marriage", "wealth", "general"],
    )


@yoga_detector
def detect_ruchaka_yoga(chart: NatalChart) -> YogaResult:
    """
    Ruchaka Yoga — Mars in Kendra in own/exaltation sign.
    Effects: courage, military leadership, physical vitality.
    Source: BPHS ch. 35
    """
    return _detect_mahapurusha(
        PlanetName.MARS, "Ruchaka Yoga", chart,
        "BPHS ch. 35", ["career", "health", "general"],
    )


@yoga_detector
def detect_bhadra_yoga(chart: NatalChart) -> YogaResult:
    """
    Bhadra Yoga — Mercury in Kendra in own/exaltation sign.
    Effects: intelligence, communication, business acumen.
    Source: BPHS ch. 35
    """
    return _detect_mahapurusha(
        PlanetName.MERCURY, "Bhadra Yoga", chart,
        "BPHS ch. 35", ["career", "education", "general"],
    )


@yoga_detector
def detect_shasha_yoga(chart: NatalChart) -> YogaResult:
    """
    Shasha Yoga — Saturn in Kendra in own/exaltation sign.
    Effects: leadership, discipline, longevity, property.
    Source: BPHS ch. 35
    """
    return _detect_mahapurusha(
        PlanetName.SATURN, "Shasha Yoga", chart,
        "BPHS ch. 35", ["career", "property", "general"],
    )


@yoga_detector
def detect_gajakesari_yoga(chart: NatalChart) -> YogaResult:
    """
    Gajakesari Yoga — Jupiter in Kendra from Moon.
    Effects: wealth, fame, wisdom, good character.
    Source: BPHS ch. 36; Phaladeepika ch. 6
    """
    moon_house = _house_of(PlanetName.MOON, chart)
    jup_house  = _house_of(PlanetName.JUPITER, chart)
    dist = _house_distance(moon_house, jup_house)
    in_kendra_from_moon = dist in (1, 4, 7, 10)

    met: list[str] = []
    failed: list[str] = []

    if in_kendra_from_moon:
        met.append(f"Jupiter in {dist}th from Moon (Kendra from Moon)")
    else:
        failed.append(f"Jupiter in {dist}th from Moon — not Kendra")

    # Strengthen if both are in good dignity
    jup_strong = _is_exalted_or_own(PlanetName.JUPITER, chart)
    moon_strong = _dignity_of(PlanetName.MOON, chart) not in (Dignity.ENEMY, Dignity.DEBILITATED)
    if jup_strong:
        met.append(f"Jupiter is {_dignity_of(PlanetName.JUPITER, chart).value}")
    if moon_strong:
        met.append(f"Moon is {_dignity_of(PlanetName.MOON, chart).value}")
    else:
        failed.append(f"Moon is weakened ({_dignity_of(PlanetName.MOON, chart).value})")

    is_present = in_kendra_from_moon
    strength = 0.0
    if is_present:
        base = 0.7
        if jup_strong: base += 0.15
        if moon_strong: base += 0.10
        strength = min(1.0, base)

    severity = (
        YogaSeverity.STRONG if strength >= 0.85
        else YogaSeverity.MODERATE if strength >= 0.65
        else YogaSeverity.WEAK if is_present
        else None
    )

    return YogaResult(
        name="Gajakesari Yoga",
        is_present=is_present,
        category=YogaCategory.LUNAR_YOGA,
        severity=severity,
        strength=round(strength, 3),
        contributing_planets=[PlanetName.JUPITER, PlanetName.MOON],
        key_houses=[moon_house, jup_house],
        effect_domain=["wealth", "general", "career"],
        source="BPHS ch. 36; Phaladeepika ch. 6",
        conditions_met=met,
        conditions_failed=failed,
    )


@yoga_detector
def detect_budhaditya_yoga(chart: NatalChart) -> YogaResult:
    """
    Budhaditya Yoga — Sun and Mercury conjunct (same sign).
    Effects: intelligence, sharp intellect, writing, public recognition.
    Source: Phaladeepika ch. 6
    """
    conjunct = _are_conjunct(PlanetName.SUN, PlanetName.MERCURY, chart)
    sun_house = _house_of(PlanetName.SUN, chart)

    met: list[str] = []
    failed: list[str] = []

    if conjunct:
        met.append(f"Sun and Mercury conjunct in sign {_sign_of(PlanetName.SUN, chart)} (house {sun_house})")
    else:
        failed.append(
            f"Sun in house {sun_house}, Mercury in house {_house_of(PlanetName.MERCURY, chart)} — not conjunct"
        )

    # Quality check: Mercury combust (within 14° of Sun) weakens the yoga
    sun_lon = chart.planets[PlanetName.SUN].longitude
    mer_lon = chart.planets[PlanetName.MERCURY].longitude
    orb = abs(sun_lon - mer_lon)
    if orb > 180:
        orb = 360 - orb
    is_combust = orb <= 14.0

    strength = 0.0
    if conjunct:
        base = 0.75
        if is_combust:
            base -= 0.25
            failed.append(f"Mercury is combust (within {orb:.1f}° of Sun) — yoga weakened")
        if _dignity_of(PlanetName.MERCURY, chart) in (Dignity.EXALTED, Dignity.OWN, Dignity.MOOLATRIKONA):
            base += 0.15
            met.append(f"Mercury is {_dignity_of(PlanetName.MERCURY, chart).value} — yoga strengthened")
        strength = max(0.0, min(1.0, base))

    return YogaResult(
        name="Budhaditya Yoga",
        is_present=conjunct,
        category=YogaCategory.SOLAR_YOGA,
        severity=(
            YogaSeverity.STRONG if strength >= 0.8
            else YogaSeverity.MODERATE if strength >= 0.5
            else YogaSeverity.WEAK if conjunct
            else None
        ),
        strength=round(strength, 3),
        contributing_planets=[PlanetName.SUN, PlanetName.MERCURY],
        key_houses=[sun_house],
        effect_domain=["education", "career", "general"],
        source="Phaladeepika ch. 6",
        conditions_met=met,
        conditions_failed=failed,
    )


@yoga_detector
def detect_raj_yoga(chart: NatalChart) -> YogaResult:
    """
    Raja Yoga — Lord of a Kendra house and lord of a Kona house are connected
    (conjunct, mutual aspect, or exchange / parivartana).

    This is a composite detection for the most common form of Raja Yoga.
    Source: BPHS ch. 34
    """
    kendra_houses = [1, 4, 7, 10]
    kona_houses   = [1, 5, 9]

    kendra_lords = {chart.bhavas[h].lord for h in kendra_houses}
    kona_lords   = {chart.bhavas[h].lord for h in kona_houses}

    # Planets that lord both a kendra and kona (natural yogakarakas)
    yogakaraka_planets = kendra_lords & kona_lords
    # Remove Sun/Moon as lagna lords if lagna is 5th/9th sign from itself (trivial case)

    # Check connections between kendra lords and kona lords
    connections: list[tuple[PlanetName, PlanetName, str]] = []

    for kp in kendra_lords:
        for kop in kona_lords:
            if kp == kop:
                continue
            # Conjunction
            if _are_conjunct(kp, kop, chart):
                connections.append((kp, kop, "conjunction"))
            # Exchange (parivartana)
            elif (
                _sign_of(kp, chart) in _get_own_signs(kop)
                and _sign_of(kop, chart) in _get_own_signs(kp)
            ):
                connections.append((kp, kop, "parivartana"))

    is_present = bool(connections) or bool(yogakaraka_planets)
    met: list[str] = []
    failed: list[str] = []

    if yogakaraka_planets:
        for p in yogakaraka_planets:
            met.append(f"{p.value.title()} lords both Kendra and Kona — natural Yogakaraka")

    for kp, kop, conn_type in connections:
        met.append(
            f"Kendra lord {kp.value.title()} and Kona lord {kop.value.title()} in {conn_type}"
        )

    if not is_present:
        failed.append("No Kendra-Kona lord connection found")

    # Strength: based on number and quality of connections
    strength = 0.0
    if yogakaraka_planets:
        strength += 0.5 * min(1.0, len(yogakaraka_planets) / 2)
    if connections:
        strength += 0.5 * min(1.0, len(connections) / 3)
    strength = min(1.0, strength)

    involved_planets = list({p for kp, kop, _ in connections for p in [kp, kop]}
                            | yogakaraka_planets)

    return YogaResult(
        name="Raja Yoga",
        is_present=is_present,
        category=YogaCategory.RAJ_YOGA,
        severity=(
            YogaSeverity.STRONG if strength >= 0.8
            else YogaSeverity.MODERATE if strength >= 0.4
            else YogaSeverity.WEAK if is_present
            else None
        ),
        strength=round(strength, 3),
        contributing_planets=involved_planets,
        key_houses=kendra_houses + kona_houses,
        effect_domain=["career", "status", "general"],
        source="BPHS ch. 34",
        conditions_met=met,
        conditions_failed=failed,
    )


def _get_own_signs(planet: PlanetName) -> set[int]:
    """Return the set of signs owned by a planet."""
    return OWN_SIGNS.get(planet, set())


@yoga_detector
def detect_dhana_yoga(chart: NatalChart) -> YogaResult:
    """
    Dhana Yoga — Connection between 2nd and 11th house lords (wealth indicators).
    Also includes 5th lord (luck/speculation) and lagna lord.
    Source: BPHS ch. 32
    """
    lord_2  = _lord_of_house(2, chart)
    lord_11 = _lord_of_house(11, chart)
    lord_5  = _lord_of_house(5, chart)
    lord_1  = _lord_of_house(1, chart)

    # Check connections
    wealth_planets = [lord_2, lord_11, lord_5, lord_1]
    connections: list[str] = []

    if _are_conjunct(lord_2, lord_11, chart):
        connections.append(f"2nd lord ({lord_2.value}) conjunct 11th lord ({lord_11.value})")
    if _are_conjunct(lord_2, lord_5, chart):
        connections.append(f"2nd lord ({lord_2.value}) conjunct 5th lord ({lord_5.value})")
    if _house_of(lord_2, chart) == 11 or _house_of(lord_11, chart) == 2:
        connections.append(f"2nd/11th lord exchange or placement")
    if _house_of(lord_11, chart) in (1, 2, 5, 9, 11):
        connections.append(f"11th lord ({lord_11.value}) in auspicious house {_house_of(lord_11, chart)}")

    is_present = bool(connections)
    strength = min(1.0, len(connections) * 0.3) if is_present else 0.0

    # Boost if both 2nd and 11th lords are strong
    if _is_exalted_or_own(lord_2, chart) and _is_exalted_or_own(lord_11, chart):
        strength = min(1.0, strength + 0.2)

    return YogaResult(
        name="Dhana Yoga",
        is_present=is_present,
        category=YogaCategory.DHANA_YOGA,
        severity=(
            YogaSeverity.STRONG if strength >= 0.8
            else YogaSeverity.MODERATE if strength >= 0.4
            else YogaSeverity.WEAK if is_present
            else None
        ),
        strength=round(strength, 3),
        contributing_planets=[p for p in set(wealth_planets) if is_present],
        key_houses=[2, 11, 5],
        effect_domain=["wealth", "finance"],
        source="BPHS ch. 32",
        conditions_met=connections,
        conditions_failed=[] if is_present else ["No 2nd/11th lord connection found"],
    )


@yoga_detector
def detect_amala_yoga(chart: NatalChart) -> YogaResult:
    """
    Amala Yoga — A natural benefic planet occupies the 10th house from Lagna or Moon.
    Effects: fame, spotless reputation, good career.
    Source: Phaladeepika ch. 6
    """
    benefics = [PlanetName.JUPITER, PlanetName.VENUS, PlanetName.MERCURY, PlanetName.MOON]
    moon_house = _house_of(PlanetName.MOON, chart)

    benefics_in_10th_from_lagna = [
        p for p in benefics if _house_of(p, chart) == 10
    ]
    benefics_in_10th_from_moon = [
        p for p in benefics
        if _house_distance(moon_house, _house_of(p, chart)) == 10
    ]

    is_present = bool(benefics_in_10th_from_lagna or benefics_in_10th_from_moon)
    all_contributing = list(set(benefics_in_10th_from_lagna + benefics_in_10th_from_moon))

    met: list[str] = []
    if benefics_in_10th_from_lagna:
        met.append(f"Benefic(s) {[p.value for p in benefics_in_10th_from_lagna]} in 10th from Lagna")
    if benefics_in_10th_from_moon:
        met.append(f"Benefic(s) {[p.value for p in benefics_in_10th_from_moon]} in 10th from Moon")

    strength = min(1.0, len(all_contributing) * 0.4) if is_present else 0.0

    return YogaResult(
        name="Amala Yoga",
        is_present=is_present,
        category=YogaCategory.SPECIAL,
        severity=YogaSeverity.STRONG if strength >= 0.7 else YogaSeverity.MODERATE if is_present else None,
        strength=round(strength, 3),
        contributing_planets=all_contributing,
        key_houses=[10],
        effect_domain=["career", "reputation"],
        source="Phaladeepika ch. 6",
        conditions_met=met,
        conditions_failed=[] if is_present else ["No natural benefic in 10th from Lagna or Moon"],
    )


@yoga_detector
def detect_vesi_vosi_yoga(chart: NatalChart) -> YogaResult:
    """
    Vesi Yoga: Planets (other than Moon) in 2nd from Sun → intelligent, wealthy.
    Vosi Yoga: Planets (other than Moon) in 12th from Sun → scholarly.
    Ubhayachari Yoga: Planets on BOTH sides → kingly qualities.
    Source: Phaladeepika ch. 6
    """
    sun_house = _house_of(PlanetName.SUN, chart)
    house_after_sun  = (sun_house % 12) + 1        # 2nd from Sun
    house_before_sun = ((sun_house - 2) % 12) + 1  # 12th from Sun

    planets_after  = [
        p for p in PlanetName
        if p not in (PlanetName.SUN, PlanetName.MOON, PlanetName.RAHU, PlanetName.KETU)
        and _house_of(p, chart) == house_after_sun
    ]
    planets_before = [
        p for p in PlanetName
        if p not in (PlanetName.SUN, PlanetName.MOON, PlanetName.RAHU, PlanetName.KETU)
        and _house_of(p, chart) == house_before_sun
    ]

    has_vesi  = bool(planets_after)
    has_vosi  = bool(planets_before)
    has_ubhay = has_vesi and has_vosi

    if has_ubhay:
        yoga_name = "Ubhayachari Yoga"
    elif has_vesi:
        yoga_name = "Vesi Yoga"
    elif has_vosi:
        yoga_name = "Vosi Yoga"
    else:
        yoga_name = "Vesi/Vosi Yoga"

    is_present = has_vesi or has_vosi
    contributing = planets_after + planets_before
    met: list[str] = []
    if planets_after:
        met.append(f"Planets in 2nd from Sun (Vesi): {[p.value for p in planets_after]}")
    if planets_before:
        met.append(f"Planets in 12th from Sun (Vosi): {[p.value for p in planets_before]}")

    return YogaResult(
        name=yoga_name,
        is_present=is_present,
        category=YogaCategory.SOLAR_YOGA,
        severity=YogaSeverity.STRONG if has_ubhay else YogaSeverity.MODERATE if is_present else None,
        strength=0.7 if has_ubhay else (0.5 if is_present else 0.0),
        contributing_planets=contributing,
        key_houses=[sun_house, house_after_sun, house_before_sun],
        effect_domain=["career", "general"],
        source="Phaladeepika ch. 6",
        conditions_met=met,
        conditions_failed=[] if is_present else ["No planets in 2nd or 12th from Sun"],
    )


# ─────────────────────────────────────────────────────────────────────────────
# Dosha detectors
# ─────────────────────────────────────────────────────────────────────────────

@dosha_detector
def detect_mangal_dosha(chart: NatalChart) -> DoshaResult:
    """
    Mangal Dosha (Kuja Dosha) — Mars in houses 1, 2, 4, 7, 8, or 12.
    Primarily affects marriage; severity varies by house and sign.
    Source: Phaladeepika; Muhurta Chintamani

    Classical cancellations reduce severity:
        - Mars in own/exaltation sign
        - Mars in Aries or Scorpio in the dosha house
        - Lagna is Aries, Scorpio, or Capricorn
        - Venus occupies Lagna
        - Mars in 2nd of Gemini or Virgo
        - Both partners have Mangal Dosha (cancels out in matching)
    """
    mars_house = _house_of(PlanetName.MARS, chart)
    mangal_houses = {1, 2, 4, 7, 8, 12}
    is_present = mars_house in mangal_houses

    # Severity by house (classical weighting: 7th is worst, then 8th, then 1st)
    severity_map = {7: 1.0, 8: 0.9, 1: 0.8, 4: 0.7, 12: 0.6, 2: 0.5}
    base_severity = severity_map.get(mars_house, 0.0)

    cancellations: list[str] = []
    severity_reduction = 0.0

    if is_present:
        mars_dignity = _dignity_of(PlanetName.MARS, chart)
        if mars_dignity in (Dignity.EXALTED, Dignity.OWN, Dignity.MOOLATRIKONA):
            cancellations.append(f"Mars in {mars_dignity.value} — Dosha partially cancelled")
            severity_reduction += 0.3

        mars_sign = _sign_of(PlanetName.MARS, chart)
        if mars_sign in (1, 8):  # Aries or Scorpio (own signs)
            cancellations.append("Mars in own sign (Aries/Scorpio) — Dosha cancelled")
            severity_reduction += 0.4

        if chart.lagna_sign in (1, 8, 10):  # Aries, Scorpio, Capricorn lagna
            cancellations.append(f"Lagna is {chart.lagna_sign_name} — Dosha significantly reduced")
            severity_reduction += 0.3

        venus_in_lagna = _house_of(PlanetName.VENUS, chart) == 1
        if venus_in_lagna:
            cancellations.append("Venus in Lagna — Dosha reduced")
            severity_reduction += 0.2

        # Jupiter aspecting Mars
        if _aspects_house(PlanetName.JUPITER, mars_house, chart):
            cancellations.append("Jupiter aspects Mars — Dosha reduced")
            severity_reduction += 0.2

    final_severity = max(0.0, min(1.0, base_severity - severity_reduction)) if is_present else 0.0

    return DoshaResult(
        name="Mangal Dosha (Kuja Dosha)",
        is_present=is_present,
        category=DoshaCategory.MANGAL,
        severity=round(final_severity, 3),
        trigger_planets=[PlanetName.MARS],
        trigger_houses=[mars_house] if is_present else [],
        effect_domain=["marriage", "relationships"],
        cancellation_factors=cancellations,
        source="Phaladeepika; Muhurta Chintamani",
    )


@dosha_detector
def detect_kala_sarpa_dosha(chart: NatalChart) -> DoshaResult:
    """
    Kala Sarpa Dosha — All 7 classical planets (not Rahu/Ketu) are hemmed
    between Rahu and Ketu (within the arc from Rahu to Ketu in one direction).

    Source: Disputed — not in BPHS; popular in modern Parashari practice.
    Note: Classified as debated dosha; included for completeness.
    """
    rahu_lon = chart.planets[PlanetName.RAHU].longitude
    ketu_lon = chart.planets[PlanetName.KETU].longitude

    # Arc from Rahu to Ketu going forward (Rahu → Ketu clockwise)
    # All planets must fall within this arc
    classical_planets = [
        PlanetName.SUN, PlanetName.MOON, PlanetName.MARS,
        PlanetName.MERCURY, PlanetName.JUPITER, PlanetName.VENUS, PlanetName.SATURN,
    ]

    def in_arc(planet_lon: float, start: float, end: float) -> bool:
        """Check if planet_lon is in the arc from start to end (going forward 0–360)."""
        if start <= end:
            return start <= planet_lon <= end
        else:  # arc crosses 0°
            return planet_lon >= start or planet_lon <= end

    # Two arcs: Rahu→Ketu and Ketu→Rahu
    # Check if all planets fall in the Rahu→Ketu arc
    arc_rahu_to_ketu_end = ketu_lon
    arc_rahu_to_ketu_start = rahu_lon

    planets_in_rahu_ketu_arc = [
        p for p in classical_planets
        if in_arc(chart.planets[p].longitude, arc_rahu_to_ketu_start, arc_rahu_to_ketu_end)
    ]
    planets_in_ketu_rahu_arc = [
        p for p in classical_planets
        if in_arc(chart.planets[p].longitude, ketu_lon, rahu_lon)
    ]

    full_kala_sarpa = len(planets_in_rahu_ketu_arc) == 7
    full_kala_amrita = len(planets_in_ketu_rahu_arc) == 7  # reverse = Kala Amrita (mixed effects)

    is_present = full_kala_sarpa or full_kala_amrita

    # Cancellations: any planet outside the Rahu-Ketu axis
    cancellations: list[str] = []
    if not is_present and len(planets_in_rahu_ketu_arc) >= 5:
        cancellations.append("Partial Kala Sarpa — not all planets hemmed")

    severity = 0.8 if full_kala_sarpa else (0.6 if full_kala_amrita else 0.0)

    return DoshaResult(
        name="Kala Sarpa Dosha" if full_kala_sarpa else "Kala Amrita Dosha" if full_kala_amrita else "Kala Sarpa Dosha",
        is_present=is_present,
        category=DoshaCategory.KALA_SARPA,
        severity=round(severity, 3),
        trigger_planets=[PlanetName.RAHU, PlanetName.KETU],
        trigger_houses=[
            _house_of(PlanetName.RAHU, chart),
            _house_of(PlanetName.KETU, chart),
        ],
        effect_domain=["general", "career", "health"],
        cancellation_factors=cancellations,
        source="Modern Parashari tradition (not in BPHS — debated)",
    )


@dosha_detector
def detect_grahan_dosha(chart: NatalChart) -> DoshaResult:
    """
    Grahan Dosha (Eclipse Dosha) — Sun or Moon conjunct Rahu or Ketu (same sign).
    Affects health, longevity, and general well-being.
    Source: BPHS ch. 81
    """
    shadow_planets = [PlanetName.RAHU, PlanetName.KETU]
    luminaries = [PlanetName.SUN, PlanetName.MOON]

    afflicted_pairs: list[tuple[PlanetName, PlanetName]] = []
    for luminary in luminaries:
        for shadow in shadow_planets:
            if _are_conjunct(luminary, shadow, chart):
                afflicted_pairs.append((luminary, shadow))

    is_present = bool(afflicted_pairs)
    severity_base = min(1.0, len(afflicted_pairs) * 0.5)

    trigger_planets: list[PlanetName] = []
    trigger_houses: list[int] = []
    cancellations: list[str] = []

    for luminary, shadow in afflicted_pairs:
        trigger_planets.extend([luminary, shadow])
        trigger_houses.append(_house_of(luminary, chart))

    trigger_planets = list(set(trigger_planets))
    trigger_houses = list(set(trigger_houses))

    # Jupiter aspecting the afflicted luminary reduces dosha
    for luminary, _ in afflicted_pairs:
        if _aspects_house(PlanetName.JUPITER, _house_of(luminary, chart), chart):
            cancellations.append(f"Jupiter aspects {luminary.value} — Dosha reduced")
            severity_base *= 0.6

    domains = []
    if any(p == PlanetName.SUN for p, _ in afflicted_pairs):
        domains.append("health")
        domains.append("father")
    if any(p == PlanetName.MOON for p, _ in afflicted_pairs):
        domains.append("mental_health")
        domains.append("mother")

    return DoshaResult(
        name="Grahan Dosha",
        is_present=is_present,
        category=DoshaCategory.GRAHAN,
        severity=round(severity_base, 3),
        trigger_planets=trigger_planets,
        trigger_houses=trigger_houses,
        effect_domain=domains or ["general"],
        cancellation_factors=cancellations,
        source="BPHS ch. 81",
    )


@dosha_detector
def detect_kemdrum_yoga(chart: NatalChart) -> DoshaResult:
    """
    Kemdrum Yoga (Moon isolation dosha) — Moon has no planet in the 2nd or 12th
    from it (in the sign immediately before or after Moon's sign), and no planet
    conjunct Moon. Causes poverty, hardship, and mental instability.

    Note: Kemdrum is technically a "yoga" in classical texts but functions as a dosha.
    Source: BPHS ch. 37
    """
    moon_house = _house_of(PlanetName.MOON, chart)
    second_from_moon  = (moon_house % 12) + 1
    twelfth_from_moon = ((moon_house - 2) % 12) + 1

    non_lunar_planets = [
        p for p in PlanetName
        if p not in (PlanetName.MOON, PlanetName.RAHU, PlanetName.KETU)
    ]

    planets_adjacent = [
        p for p in non_lunar_planets
        if _house_of(p, chart) in (second_from_moon, twelfth_from_moon, moon_house)
    ]

    is_present = len(planets_adjacent) == 0

    cancellations: list[str] = []
    if not is_present:
        for p in planets_adjacent:
            cancellations.append(
                f"{p.value.title()} in house {_house_of(p, chart)} — Kemdrum cancelled"
            )

    # Additional cancellation: Moon in Kendra from Lagna
    if _house_of(PlanetName.MOON, chart) in (1, 4, 7, 10):
        if is_present:
            cancellations.append("Moon in Kendra from Lagna — Kemdrum partially mitigated")
            is_present = False  # Full cancellation per classical texts

    severity = 0.75 if is_present else 0.0

    return DoshaResult(
        name="Kemdrum Yoga",
        is_present=is_present,
        category=DoshaCategory.ISOLATION,
        severity=round(severity, 3),
        trigger_planets=[PlanetName.MOON],
        trigger_houses=[moon_house],
        effect_domain=["mental_health", "general", "wealth"],
        cancellation_factors=cancellations,
        source="BPHS ch. 37",
    )


@dosha_detector
def detect_guru_chandala_yoga(chart: NatalChart) -> DoshaResult:
    """
    Guru Chandala Yoga — Jupiter conjunct Rahu (same sign).
    Corrupts Jupiter's significations: ethics, spirituality, teachers, children.
    Source: Phaladeepika; Jataka Parijata
    """
    conjunct = _are_conjunct(PlanetName.JUPITER, PlanetName.RAHU, chart)
    jup_house = _house_of(PlanetName.JUPITER, chart)

    cancellations: list[str] = []
    severity = 0.0

    if conjunct:
        severity = 0.7
        # Reduction if Jupiter is very strong (exalted/own)
        if _dignity_of(PlanetName.JUPITER, chart) in (Dignity.EXALTED, Dignity.OWN):
            severity *= 0.5
            cancellations.append("Jupiter in exaltation/own sign — Guru Chandala partially cancelled")

    return DoshaResult(
        name="Guru Chandala Yoga",
        is_present=conjunct,
        category=DoshaCategory.CURSE,
        severity=round(severity, 3),
        trigger_planets=[PlanetName.JUPITER, PlanetName.RAHU],
        trigger_houses=[jup_house] if conjunct else [],
        effect_domain=["education", "spirituality", "children"],
        cancellation_factors=cancellations,
        source="Phaladeepika; Jataka Parijata",
    )


@dosha_detector
def detect_shrapit_dosha(chart: NatalChart) -> DoshaResult:
    """
    Shrapit Dosha — Saturn conjunct Rahu (same sign).
    Indicates accumulated negative karma; affects longevity, career, and relationships.
    Source: Popular modern Parashari (not explicitly in BPHS)
    """
    conjunct = _are_conjunct(PlanetName.SATURN, PlanetName.RAHU, chart)
    sat_house = _house_of(PlanetName.SATURN, chart)

    cancellations: list[str] = []
    severity = 0.0

    if conjunct:
        severity = 0.65
        if _dignity_of(PlanetName.SATURN, chart) in (Dignity.EXALTED, Dignity.OWN):
            severity *= 0.6
            cancellations.append("Saturn in exaltation/own sign — Shrapit Dosha reduced")

    return DoshaResult(
        name="Shrapit Dosha",
        is_present=conjunct,
        category=DoshaCategory.CURSE,
        severity=round(severity, 3),
        trigger_planets=[PlanetName.SATURN, PlanetName.RAHU],
        trigger_houses=[sat_house] if conjunct else [],
        effect_domain=["career", "health", "general"],
        cancellation_factors=cancellations,
        source="Modern Parashari tradition",
    )


# ─────────────────────────────────────────────────────────────────────────────
# Public API
# ─────────────────────────────────────────────────────────────────────────────

def detect_all_yogas(chart: NatalChart) -> list[YogaResult]:
    """
    Run all registered yoga detectors against a natal chart.

    All detectors are pure functions — no LLM, no external calls.
    Results include both present and absent yogas (is_present flag indicates which).

    Args:
        chart: The natal chart to analyze.

    Returns:
        List of YogaResult objects (one per registered detector).
    """
    return [detector(chart) for detector in _YOGA_DETECTORS]


def detect_all_doshas(chart: NatalChart) -> list[DoshaResult]:
    """
    Run all registered dosha detectors against a natal chart.

    Args:
        chart: The natal chart to analyze.

    Returns:
        List of DoshaResult objects (one per registered detector).
    """
    return [detector(chart) for detector in _DOSHA_DETECTORS]


def detect_all_yogas_and_doshas(chart: NatalChart) -> YogaDoshaBundle:
    """
    Run all yoga and dosha detectors and return a complete bundle.

    Primary entry point for the YogaDoshaAgent. This is the only function
    that agent calls — all sub-detections are internal.

    Args:
        chart: The natal chart to analyze.

    Returns:
        YogaDoshaBundle with full yoga and dosha analysis.
    """
    yogas  = detect_all_yogas(chart)
    doshas = detect_all_doshas(chart)

    return YogaDoshaBundle(
        chart_id=chart.chart_id,
        yogas=yogas,
        doshas=doshas,
    )
